package com.example.core.export

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.util.Base64
import com.example.core.linkparse.ShareLinkParser
import com.example.core.model.ProbeResult
import com.example.core.model.ShareLinkConfig
import org.json.JSONArray
import org.json.JSONObject
import java.util.Locale

object ResultExporter {

    /**
     * Exports plain IP list (one per line, bracketed if IPv6)
     */
    fun toPlainTxt(results: List<ProbeResult>, includePort: Boolean = false): String {
        return results.joinToString("\n") { r ->
            if (includePort) {
                r.hostPortString
            } else {
                r.ip
            }
        }
    }

    /**
     * Exports CSV with full measurement metrics
     */
    fun toCsv(results: List<ProbeResult>): String {
        val header = "IP,Port,Colo,AvgLatencyMs,MinLatencyMs,MaxLatencyMs,JitterMs,LossPercent,ThroughputMbps,TTFBMs,TLSVersion,Score"
        val lines = results.map { r ->
            String.format(
                Locale.US,
                "%s,%d,%s,%.1f,%.1f,%.1f,%.1f,%.1f,%s,%s,%s,%.1f",
                r.ip,
                r.port,
                r.colo,
                r.avgLatencyMs,
                r.minLatencyMs,
                r.maxLatencyMs,
                r.jitterMs,
                r.packetLossPercent,
                r.throughputMbps?.let { String.format(Locale.US, "%.2f", it) } ?: "n/a",
                r.ttfbMs?.toString() ?: "n/a",
                r.tlsVersion,
                r.score
            )
        }
        return (listOf(header) + lines).joinToString("\n")
    }

    /**
     * Exports JSON array of results
     */
    fun toJson(results: List<ProbeResult>): String {
        val array = JSONArray()
        for (r in results) {
            val obj = JSONObject()
            obj.put("ip", r.ip)
            obj.put("port", r.port)
            obj.put("isIpv6", r.isIpv6)
            obj.put("colo", r.colo)
            obj.put("avgLatencyMs", r.avgLatencyMs)
            obj.put("minLatencyMs", r.minLatencyMs)
            obj.put("maxLatencyMs", r.maxLatencyMs)
            obj.put("jitterMs", r.jitterMs)
            obj.put("packetLossPercent", r.packetLossPercent)
            if (r.throughputMbps != null) obj.put("throughputMbps", r.throughputMbps)
            if (r.ttfbMs != null) obj.put("ttfbMs", r.ttfbMs)
            obj.put("tlsVersion", r.tlsVersion)
            obj.put("score", r.score)
            obj.put("isHealthy", r.isHealthy)
            array.put(obj)
        }
        return array.toString(2)
    }

    /**
     * Exports /etc/hosts format lines
     */
    fun toHostsFormat(results: List<ProbeResult>, hostnames: List<String> = listOf("speed.cloudflare.com")): String {
        val builder = StringBuilder()
        builder.appendLine("# Generated by Clean IP Scanner")
        for (r in results.take(10)) {
            val line = "${r.ip}\t${hostnames.joinToString(" ")}"
            builder.appendLine(line)
        }
        return builder.toString()
    }

    /**
     * Rewrites proxy share links with clean IPs
     */
    fun toRewrittenShareLinks(results: List<ProbeResult>, config: ShareLinkConfig): List<String> {
        return results.map { r ->
            ShareLinkParser.rewriteWithCleanIp(config, r.ip)
        }
    }

    /**
     * Generates top 20 VLESS configs from a raw VLESS link and clean probe results
     */
    fun toTop20VlessConfigs(rawVlessLink: String, results: List<ProbeResult>, maxCount: Int = 20): List<String> {
        return ShareLinkParser.generateTop20VlessConfigs(rawVlessLink, results, maxCount)
    }

    /**
     * Encodes top 20 VLESS configs as a Base64 subscription string
     */
    fun toTop20VlessSubscriptionBase64(rawVlessLink: String, results: List<ProbeResult>, maxCount: Int = 20): String {
        val configs = toTop20VlessConfigs(rawVlessLink, results, maxCount).joinToString("\n")
        return try {
            Base64.encodeToString(configs.toByteArray(Charsets.UTF_8), Base64.NO_WRAP)
        } catch (_: Throwable) {
            java.util.Base64.getEncoder().encodeToString(configs.toByteArray(Charsets.UTF_8))
        }
    }

    /**
     * Encodes rewritten share links as Base64 subscription
     */
    fun toSubscriptionBase64(results: List<ProbeResult>, config: ShareLinkConfig): String {
        val links = toRewrittenShareLinks(results, config).joinToString("\n")
        return try {
            Base64.encodeToString(links.toByteArray(Charsets.UTF_8), Base64.NO_WRAP)
        } catch (_: Throwable) {
            java.util.Base64.getEncoder().encodeToString(links.toByteArray(Charsets.UTF_8))
        }
    }

    fun copyToClipboard(context: Context, label: String, text: String): Boolean {
        return try {
            val cm = context.getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager
            val clip = ClipData.newPlainText(label, text)
            cm?.setPrimaryClip(clip)
            true
        } catch (_: Exception) {
            false
        }
    }
}
